# Generated by Django 5.0.6 on 2026-05-19 01:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0002_notifications_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(blank=True, max_length=120)),
                ('duree_estimee_heures', models.PositiveSmallIntegerField(default=1)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrePointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut_officielle', models.TimeField(default='09:00')),
                ('heure_fin_officielle', models.TimeField(default='18:00')),
                ('tolerance_retard_minutes', models.PositiveSmallIntegerField(default=10)),
                ('heures_minimum_jour', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('points_presence_normale', models.IntegerField(default=10)),
                ('penalite_retard', models.IntegerField(default=5)),
                ('penalite_sortie_anticipee', models.IntegerField(default=5)),
                ('bonus_heures_supplementaires', models.IntegerField(default=3)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='localisation',
            field=models.CharField(blank=True, default='Casablanca', max_length=255),
        ),
        migrations.AddField(
            model_name='poste',
            name='est_direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poste',
            name='est_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poste',
            name='rang_hierarchique',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('audience', models.CharField(choices=[('tous', 'Tous'), ('departement', 'Departement'), ('role', 'Role')], default='tous', max_length=30)),
                ('role_cible', models.CharField(blank=True, max_length=40)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiee'), ('archivee', 'Archivee')], default='brouillon', max_length=30)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_evenement', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/actualites/')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.departement')),
            ],
        ),
        migrations.CreateModel(
            name='ComptePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_points', models.IntegerField(default=0)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_points', to='hr.employe')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_attente', 'En attente'), ('cloturee', 'Cloturee')], default='ouverte', max_length=30)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_derniere_reponse', models.DateTimeField(default=django.utils.timezone.now)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_rh', to='hr.employe')),
                ('responsable_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(default=django.utils.timezone.localdate)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('assignee', 'Assignee'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('en_retard', 'En retard'), ('annulee', 'Annulee')], default='assignee', max_length=30)),
                ('date_completion', models.DateField(blank=True, null=True)),
                ('assigne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_assignees', to='hr.employe')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='hr.formation')),
            ],
        ),
        migrations.CreateModel(
            name='MessageRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('lu', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hr.conversationrh')),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_recus', to='accounts.utilisateurprofile')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='accounts.utilisateurprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('heure_entree', models.DateTimeField(blank=True, null=True)),
                ('heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('total_heures', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('statut', models.CharField(choices=[('present', 'Present'), ('retard', 'Retard'), ('sortie_anticipee', 'Sortie anticipee'), ('incomplet', 'Incomplet'), ('absent', 'Absent')], default='incomplet', max_length=40)),
                ('points_calcules', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='hr.employe')),
            ],
            options={
                'ordering': ['-date', '-heure_entree'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/produits/')),
                ('cout_points', models.PositiveIntegerField(default=0)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.categorieproduit')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('cout_total_points', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvee'), ('refusee', 'Refusee'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='en_attente', max_length=30)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('points_deduits', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_produits', to='hr.employe')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.produit')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_attribution', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('attribue', 'Attribue'), ('livre', 'Livre'), ('retourne', 'Retourne'), ('perdu', 'Perdu'), ('remplace', 'Remplace')], default='attribue', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='hr.employe')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_reclamation', models.CharField(choices=[('points', 'Points'), ('pointage', 'Pointage'), ('conge', 'Conge'), ('materiel', 'Materiel'), ('salaire', 'Salaire'), ('document', 'Document'), ('autre', 'Autre')], max_length=30)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee'), ('cloturee', 'Cloturee')], default='ouverte', max_length=30)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('reponse_rh', models.TextField(blank=True)),
                ('points_accordes', models.PositiveIntegerField(default=0)),
                ('action_points_appliquee', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='hr.employe')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AjustementPointsManuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adjustement', models.CharField(choices=[('ajout', 'Ajout'), ('retrait', 'Retrait'), ('correction', 'Correction'), ('remboursement', 'Remboursement')], max_length=30)),
                ('nombre_points', models.PositiveIntegerField()),
                ('motif_obligatoire', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_crees', to='accounts.utilisateurprofile')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements_points', to='hr.employe')),
                ('reclamation_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.reclamationrh')),
            ],
        ),
        migrations.CreateModel(
            name='Remuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='MAD', max_length=8)),
                ('date_effet', models.DateField(default=django.utils.timezone.localdate)),
                ('actif', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='hr.employe')),
            ],
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours_disponibles', models.DecimalField(decimal_places=2, default=22, max_digits=6)),
                ('jours_utilises', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conge', to='hr.employe')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementSoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(max_length=40)),
                ('jours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_solde', to='hr.demandeconge')),
                ('solde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='hr.soldeconge')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('gain', 'Gain'), ('deduction', 'Deduction'), ('achat', 'Achat'), ('correction', 'Correction'), ('remboursement', 'Remboursement')], max_length=30)),
                ('source', models.CharField(choices=[('pointage', 'Pointage'), ('boutique', 'Boutique'), ('conge', 'Conge'), ('formation', 'Formation'), ('manuel', 'Manuel'), ('reclamation', 'Reclamation')], max_length=30)),
                ('points', models.IntegerField()),
                ('solde_avant', models.IntegerField()),
                ('solde_apres', models.IntegerField()),
                ('description', models.TextField()),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('objet_lie', models.CharField(blank=True, max_length=120)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilisateurprofile')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_points', to='hr.employe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='affectationformation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['assignee', 'en_cours'])), fields=('formation', 'employe'), name='unique_formation_active_employe'),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.UniqueConstraint(fields=('employe', 'date'), name='unique_pointage_employe_date'),
        ),
    ]
