# Generated by Django 5.0.6 on 2026-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_categorieproduit_formation_parametrepointage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationformation',
            name='points_attribues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='points_recompense',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
