# Generated by Django 5.0.6 on 2026-05-20 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0004_affectationformation_points_attribues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Shift', max_length=160)),
                ('lieu', models.CharField(blank=True, default='Casablanca', max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('pause_minutes', models.PositiveSmallIntegerField(default=0)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publie'), ('ouvert', 'Shift ouvert'), ('termine', 'Termine'), ('annule', 'Annule')], default='brouillon', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_crees', to='accounts.utilisateurprofile')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='hr.departement')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='hr.employe')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='hr.service')),
            ],
            options={
                'ordering': ['date_debut', 'employe__nom'],
            },
        ),
        migrations.AddField(
            model_name='pointage',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='hr.planningshift'),
        ),
        migrations.CreateModel(
            name='TacheEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('a_faire', 'A faire'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('annulee', 'Annulee')], default='a_faire', max_length=30)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_crees', to='accounts.utilisateurprofile')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='hr.departement')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='hr.employe')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='hr.planningshift')),
                ('terminee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_terminees', to='accounts.utilisateurprofile')),
            ],
            options={
                'ordering': ['statut', 'date_limite', '-date_creation'],
            },
        ),
    ]
